#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 desktop-ui contributors

# Apply a cursor theme and size to desktop and legacy cursor consumers.
set -euo pipefail

usage() {
    printf 'Usage: %s CURSOR_THEME [SIZE]\n' "${0##*/}" >&2
}

if (( $# < 1 || $# > 2 )) || [[ -z $1 ]]; then
    usage
    exit 64
fi

theme=$1
size=${2:-24}
if [[ $theme =~ [[:cntrl:]] ]]; then
    printf '%s: theme names cannot contain control characters\n' "${0##*/}" >&2
    exit 64
fi
if [[ ! $size =~ ^[0-9]{1,3}$ ]] || (( 10#$size < 1 || 10#$size > 512 )); then
    printf '%s: cursor size must be an integer from 1 to 512\n' "${0##*/}" >&2
    exit 64
fi
size=$((10#$size))

acquire_theme_lock() {
    command -v flock >/dev/null 2>&1 || return 0
    local lock_root=${XDG_RUNTIME_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}}
    local previous_umask
    mkdir -p -- "$lock_root"
    previous_umask=$(umask)
    umask 077
    exec 9>"$lock_root/desktop-ui-theming-${UID}.lock"
    umask "$previous_umask"
    flock 9
}

try_gsettings() {
    local schema=$1
    local key=$2
    local value=$3
    command -v gsettings >/dev/null 2>&1 || return 0
    if [[ $(gsettings writable "$schema" "$key" 2>/dev/null || true) == true ]]; then
        gsettings set "$schema" "$key" "$value" 2>/dev/null || true
    fi
}

write_cursor_inheritance() {
    local directory=$HOME/.icons/default
    local destination=$directory/index.theme
    local temporary

    mkdir -p -- "$directory"
    temporary=$(mktemp "${destination}.tmp.XXXXXX")
    {
        printf '[Icon Theme]\n'
        printf 'Name=Default\n'
        printf 'Comment=Default cursor theme generated by desktop-ui\n'
        printf 'Inherits=%s\n' "$theme"
    } >"$temporary"

    if [[ -e $destination ]]; then
        chmod --reference="$destination" "$temporary" 2>/dev/null || true
    else
        chmod 0644 "$temporary"
    fi
    mv -f -- "$temporary" "$destination"
}

acquire_theme_lock

try_gsettings org.gnome.desktop.interface cursor-theme "$theme"
try_gsettings org.gnome.desktop.interface cursor-size "$size"
write_cursor_inheritance
